### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by bugzpodder** [pmmmwh/react-refresh-webpack-plugin#107]
I've been using this plugin for a while and the experience has been pretty seamless, super awesome.  Occasional breakages (on stale page I sometimes see a chunk not getting loaded) are solved by a full page reload.   I'm curious what is the plan for a 1.0 release in terms of what else is missing (I scanned the issues and didn't see anything especially outstanding), it is more difficult to get buy-in by a team when the version is 0.4.0-beta.2.

**Comment by pmmmwh** [comment]
There' some stuff that I would love to iron out before an official 1.0 release:

- Revisit socket URL detection for WDS and fix #30: this only impacts WDS integration but since CRA uses WDS it is something I want to handle
- Fix #81
- Webpack 5 support #27: This is important for libraries adopting Webpack 5, like Next.js
- Possibly even address #75

**Comment by bugzpodder** [comment]
Awesome, thanks for the awesome work, really appreciate it!  And thanks for calling out important issues on Twitter!

**Comment by pmmmwh** [comment]
https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/1#issuecomment-655367948
