### ISSUE TITLE
React-Refresh not working for bound function which returns JSX.

### ISSUE THREAD

**Issue by cincyelite22** [pmmmwh/react-refresh-webpack-plugin#125]
### Describe the bug

I have a view that is binding to a function which returns JSX:
```html
<div>
 {TestComponent()}
</div>
```
When the JSX that TestComponent returns changes, the view is not updated.

However; if the function is used in the below format, the changes to TestComponent are reflected to the view:
```html
<div>
 <TestComponent></TestComponent>
</div>
```

### Steps to reproduce

(Write your steps here:)

1. Clone the repo athttps://github.com/cincyelite22/React-Refresh-Test
2. Navigate into the examples/create-react-app folder
2. Run 'yarn install'
3. Run 'yarn start'
4. Change the value of "ReplaceMeToTest" in Dummy.js and observe that the view did not updated for the {Dummy( { val:'2. HMR Not Working ' } )} usage.
5. Uncomment one of the extra exports in Dummy.js
6. Change the value of "ReplaceMeToTest" in Dummy.js again and observe that both usages are updated in the view.

### Expected behavior
The view  should update for both types of usages of "Dummy" regardless of whether the extra unused export is present.

### Actual behavior
The view doesn't update for both usages, but weirdly starts working if an extra unused export is added.

![React-RefreshBug](https://user-images.githubusercontent.com/11810016/85420453-34b4fe80-b541-11ea-82dc-36b750a5559f.gif)

### Reproducible demo

I have cloned https://github.com/pmmmwh/react-refresh-webpack-plugin and reproduced the issue in the create react app example. You can test these changes by pulling from the repo below:
https://github.com/cincyelite22/React-Refresh-Test

**Comment by pmmmwh** [comment]
This should be intentional.

The pattern you've illustrated here is an anti-pattern - the sub-tree generated by the JSX-returning function will get pruned and recreated whenever a change occurs. I also think the semantics are different from regular JSX and generated code is quite different  (thus making it difficult to track updates)

@gaearon Can you confirm that I'm correct that this will not be supported by `react-refresh`?

**Comment by cincyelite22** [comment]
@pmmmwh I have noticed that the use case works fine if the export is camel case instead of pascal case.

**Comment by pmmmwh** [comment]
> @pmmmwh I have noticed that the use case works fine if the export is camel case instead of pascal case.

Yes, for that specific example not using pascal case will make it work.

This is because, the runtime is now not detecting the JSX-returning function as a component (when it in fact is not), and thus propagates the hot update to it's parent - which is a component. The result is that the parent component will be re-rendered and thus making update seemingly work for the function. When the parent is not a component though, this will not work and in the worst case it will yield a bail out when we propagates to root (i.e. full refresh).

**Comment by Rohitbels** [comment]
@pmmmwh  I also have a similar issue.
```
function LazyLoader(WrappedComponent) {
    return class Wrapped extends PureComponent {
        render() {
            return (
                <Suspense fallback={<h1>Loading</h1>}>
                    <WrappedComponent {...this.props} />
                </Suspense>
            );
        }
    };
}

export default LazyLoader;

```

When I lazy load this my Components using above HOC full page reload takes places.
Am I missing something here?

**Comment by pmmmwh** [comment]
> When I lazy load my Components using above HOC full page reload takes places.
> Am I missing something here?

Can you create a simple repro repo? You can fork the examples here and modify them.

Side note, you can probably return a function component?

```jsx
function LazyLoader(WrappedComponent) {
  return function Wrapped(props) {
    <Suspense fallback={<h1>Loading</h1>}>
      <WrappedComponent {...props} />
    </Suspense>
  }
}
```

**Comment by gaearon** [comment]
All of this sounds correct.

You shouldn't be "calling" components directly because this breaks Hooks, too. So you should be using JSX or createElement for them. If you don't intend that function to be treated as a component, don't use Pascal Case for it.

>When I lazy load my Components using above HOC full page reload takes places.

This sounds entirely unrelated to the issue on this thread and is a result of you using a class.

**Comment by pmmmwh** [comment]
> When I lazy load my Components using above HOC full page reload takes places.

I just did some quick tests and I cannot reproduce this issue.

(Simply add your LazyLoader into `examples/webpack-dev-server` and wrap the `LazyComponent` with it)

@Rohitbels Please open a new issue with your particular usage in it to discuss this further.
