### ISSUE TITLE
Add configuration for disable error overlay for `unhandledrejection` event

### ISSUE THREAD

**Issue by SuperOleg39** [pmmmwh/react-refresh-webpack-plugin#137]
Hello!

**Use case**
`unhandledrejection` event mostly is not a critical error for applications, but with `react-refresh` and enabled `overlay` option, it's impossible to continue develop application.
It is a problem, when developer not controlling rejected promise, for example, if promise run inside external library.

**Proposal**
Add extra option to `ErrorOverlayOptions`,  for example: `options.overlay.preventUnhandledRejectionHandle`, and check this option inside `ErrorOverlayEntry.js`

I can contribute this changes, if it's allowable logic to plugin.

**Comment by pmmmwh** [comment]
> `unhandledrejection` event mostly is not a critical error for applications

Personally, I see things differently. I think an unhandled promise rejection **IS** an error in the application, and developers have the responsibility to deal with it. I see them as **ERRORS** in the Promise realm. In worst cases, it might fail silently in production which will make your application fall into an inconsistent state that is not obvious to the user (with errors you will most likely be hit right away).

Side note - Node.js have been warning about this event for a long time that it will exit the process immediately with a non-zero exit code, hinting that they most likely see this as an error too.

> it's impossible to continue develop application

You can always close the runtime overlay - there is a close button. It is annoying, but I would argue that this annoyance is actually valuable so that you will notice these unhandled promises being thrown around.

> It is a problem, when developer not controlling rejected promise, for example, if promise run inside external library.

I think there are two problems here:

1. The library does not adequately handles the promises it triggers. This is an issue that should be directed at the library and it is a bug in the library to a certain extent.

2. You should handle that promise outside of the library. Wrap it with a try-catch block, or with a `.catch` handler. They can be empty blocks doing nothing, but they should exist to handle these cases.

I know in edge cases (e.g. if the library `void` the promise) you will be unable to handle it properly, so it should definitely be reported to the library instead.

> I can contribute this changes, if it's allowable logic to plugin.

I don't want to sound harsh but to me I fear allowing this option to be disabled hide a lot of problematic promise logic in user-space. I would want this to prompt as a hard default ...

There's another discussion to be had though - we could tone down the error-response of the event to, for example, the warning level. I have been hoping to build the `warning` experience of the overlay for a long time, and I think it might fit there.

I'll ask for some feedback from framework authors on this matter.

**Comment by SuperOleg39** [comment]
Thank you for the complete answer! Agree with your arguments, will be waiting news about warning level)
