### ISSUE TITLE
examples/webpack-plugin-serve doesn't start

### ISSUE THREAD

**Issue by bebraw** [pmmmwh/react-refresh-webpack-plugin#158]
Running the webpack-plugin-serve example of the project yields `Error: Hot Module Replacement (HMR) is not enabled! ReactRefreshWebpackPlugin requires HMR to function properly.`.

I see this is because webpack-plugin-serve expects `HotModuleReplacementPlugin` not to be injected since it takes care of it and react-refresh-webpack-plugin expects it to work. If I remove the related check from react-refresh-webpack-plugin, it works perfectly with webpack-plugin-serve.

I guess as a solution we could either:

1. Remove the check entirely (maybe not preferable)
2. Add a flag for disabling the check (likely better)
3. Detect for webpack-plugin-serve somehow and then skip the check (best?)

**Comment by pmmmwh** [comment]
I guess the main issue here is that our current heuristic to detect for HMR capability is skewed towards "user-initiated" HMR plugin injection (because we won't be able to detect plugins injected by plugins via `compiler.options.plugins`).

A more robust and general check would be to check for `context.hot` in the normal module factory, although it would fail in a much later phase (I guess it's a reasonable trade-off). I can PR that later.

**Comment by bebraw** [comment]
Yeah, that sounds like a better check. Thanks!

**Comment by bebraw** [comment]
@pmmmwh It looks like the webpack-plugin-serve is still using `0.4.0-beta.8` of **@pmmmwh/react-refresh-webpack-plugin**. Maybe there's a way to resolve against the project root or so for the package to avoid having to update the references.

I tested it against the current beta and it works very well. Thanks a lot! 👍

**Comment by friek108** [comment]
I'm getting this error after following the installation instructions with 0.4.1 - sorry but I don't fully understand the issue here to help debug - I've tried a few different variations of config but still get the error. @pmmmwh are you saying the issue is not fully resolved and we'll need to wait until it is to get it to work?

**Comment by pmmmwh** [comment]
> I'm getting this error after following the installation instructions with 0.4.1 - sorry but I don't fully understand the issue here to help debug - I've tried a few different variations of config but still get the error. @pmmmwh are you saying the issue is not fully resolved and we'll need to wait until it is to get it to work? 

Hi, can you post your Webpack config for me to take a look at what's wrong? What versions of WPS are you using? Fid you enable the `hmr` functionality?
