### ISSUE TITLE
Modifying the mobx store will crash

### ISSUE THREAD

**Issue by Eivs** [pmmmwh/react-refresh-webpack-plugin#175]
Hi, I am using mobx-react's Provider and inject API

Root component:
```javascript
const App = () => (
  <Provider store={store}>
     ......
  </Provider>
);
```

Other components:
```javascript
@inject("store")
@observer
class Button extends React.Component {
   ....
};
```

Crash after modifying the store file:
```shel
Uncaught Error: MobX Provider: The set of provided stores has changed. See: https://github.com/mobxjs/mobx-react#the-set-of-provided-stores-has-changed-error.
    at MobXProvider (mobxreact.esm.js:504)
    at renderWithHooks (react-dom.development.js?7f13:14826)
    at updateFunctionComponent (react-dom.development.js?7f13:17059)
    at beginWork (react-dom.development.js?7f13:18644)
    at HTMLUnknownElement.callCallback (react-dom.development.js?7f13:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?7f13:238)
    at invokeGuardedCallback (react-dom.development.js?7f13:293)
    at beginWork$1 (react-dom.development.js?7f13:23235)
    at performUnitOfWork (react-dom.development.js?7f13:22186)
    at workLoopSync (react-dom.development.js?7f13:22162)
```

webpack: 4.44.1
webpack-dev-server: 3.11.0
react: 16.13.1
react-dom: 16.13.1
mobx: 5.15.5
mobx-react: 6.2.5
@pmmmwh/react-refresh-webpack-plugin: 0.4.1
react-refresh: 0.8.3

**Comment by gaearon** [comment]
Please report this to MobX. Generally, it is expected that React components are able to gracefully react to any prop updates.

**Comment by pmmmwh** [comment]
In `mobx-react@6` they have clearly stated that the `Provider`/`inject` pattern is getting obsolete. That API have a lot of legacy restrictions and most likely aren't compatible with newer/upcoming React features (such as FR which is the case here) - not to mention that they are error prone and not very resilient to re-initialisation (which is what happens React refreshes the component).

I'm quite confident a resolution to this is to move away from `mobx-react`'s `Provider` and `inject` function and use React context instead. You can create your own `Provider` component, and since it is based off React primitives it most likely will work.

If a migration is painful, in the meantime you can also [make your own `inject`](https://mobx-react.js.org/recipes-migration#make-your-own-inject).

**Comment by Eivs** [comment]
I try to use React Context to replace Provider and inject, The problem is solved. Thank you everyone!
