### ISSUE TITLE
Does this plugin needs to capture errors beyond react itself.

### ISSUE THREAD

**Issue by Rohitbels** [pmmmwh/react-refresh-webpack-plugin#179]
I had an **Uncaught (in promise) error** and the overlay was displayed.

Through interceptor we have already handled the case promise rejection and displayed appropriate message.
Just that at the last chain being a get request we had not added .catch() and it was console logged.

Why this plugin has to consider this error and display overlay.

**Comment by pmmmwh** [comment]
There are two parts of the issue here, so I'll answer separately.

> Why is Uncaught Exception considered as an error?

Some points:

- Most of the time it originates from user programming errors, and it is always good to notify you during development than to allow it silently fail in production
- It is always good to properly handle promise rejections, if you really don't care you can chain a no-op `.catch(() => {})` or use try catch with an empty catch block
- To me this event equals to error in the synchronous world, and I'm not the only one that shares that view
  - Node.js have been warning about unhandled promise rejection crashing apps since v10/v12
  - All other error overlays I know of have a similar implementation

> Why does the plugin capture errors beyond the scope of React?

Short answer: this is a technical limitation.

You can read [this comment](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/139#issuecomment-657386435) for a bit of background on this.

In a future version I intend to improve the experience, especially with the new event handling in React 17.

**Comment by Rohitbels** [comment]
I agree with you @pmmmwh  
Thanks for the Reply.

Closing this as it does not break anything anyway.
