### ISSUE TITLE
How do i know if it's working?

### ISSUE THREAD

**Issue by damiangreen** [pmmmwh/react-refresh-webpack-plugin#197]
I've followed the instructions to install into an existing app that was already using `webpack-hot-middleware` + `webpack-dev-middleware`

i'm seeing no difference in the command line.
I see `[HMR] Update applied.` as per usual.

Should I remove `react-hot-loader` + `npm:@hot-loader/react-dom`

Is there some way to know if this plugin is working?

**Comment by pmmmwh** [comment]
Hi, if you edited a component and the update is reflected on your browser without a full refresh then it's working.

You should remove packages related to `react-hot-loader` - the two are not mutually compatible.

**Comment by pmmmwh** [comment]
Hi - have you manage to make it work?

**Comment by damiangreen** [comment]
hi @pmmmwh 
I did, however it seems noticably slow than hot reloader so we havent adopted it yet

**Comment by pmmmwh** [comment]
> I did, however it seems noticibly slow than hot reloader so we haven't adopted it yet

Which part of it is slower? The Babel compilation?

**Comment by damiangreen** [comment]
the hot reloading. 
I did see there is another issue related to this in this repo, but it would be difficult to create a repo for.

**Comment by pmmmwh** [comment]
> the hot reloading.

This is very hard for me to understand the underlying problem because there are many parts that constitutes the HMR experience - first there's the time for Webpack to recompile (which involves Babel), then there's the time for the updates to be served through a socket connection or an event stream, after that there's the actual JS parsing and Webpack HMR replacement and finally the React re-render.

Do you mean that the time from you making a change to the time the result propagate on the screen is slow in general, or some specific part that is slow?

**Comment by damiangreen** [comment]
yes, that's right, editing a file and waiting for the component to reload is slower than the existing react hot loader.. unfortunately

**Comment by pmmmwh** [comment]
Well unfortunately that's not something I can fix - I do not know how your build is currently setup, but you can try adding cache for Babel Loader so recompilation will be faster (with `cacheDirectory` flag). I think RHL also have a Babel plugin, and if you that is used the performative should be similar - the inherent nature of source parsing.
