### ISSUE TITLE
Warn if file containing React components and something else doesn't get a boundary

### ISSUE THREAD

**Issue by bebraw** [pmmmwh/react-refresh-webpack-plugin#206]
As far as I understand, the current logic can patch only modules that contain only React modules. It would be great to show a warning in the console or so that you are aware of this case.

Here's the related code: https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/runtime/RefreshUtils.js.

**Comment by pmmmwh** [comment]
To be specific, the fast refresh only hot update a file when we can construct a boundary, and propagate to parent if we cannot. So we technically do not know if the current update might bail out in each file cause it might have parents that are boundaries. If we warn about that, it might over fire (in some cases they are perfectly ok, such as exporting constants or even GQL queries etc.) and a lot of people might be confused what's wrong.

A warning when we reached root and bail out might be good, but at that point we're already falling back to a full refresh - which means logs will get erased by default ...

I'm not sure what to do to make the caveats more obvious tbh, and if you have some more ideas I'm more than happy to review and implement them.

**Comment by bebraw** [comment]
If possible, maybe one option would be to provide a callback where the user can override the behavior. That would allow you to force a full refresh for example and the approach would be backwards compatible. As you mention, the gotcha is that with full refresh logs are lost but at least it's the user's choice then.

I can see it's a little tricky problem due to GraphQL and other exports that are still valid. This only becomes a problem when the root of the tree isn't pure React as then the logic will fall through.

**Comment by pmmmwh** [comment]
> If possible, maybe one option would be to provide a callback where the user can override the behavior.

This is actually already configurable - in this plugin we do not control what would happen on a bail out. If you're using the WDS for example, you could use `hotOnly` instead of `hot`, and it would only warn you when it is forced to bail out, but will not actually refresh the page. We intentionally do not hold any constraint on this to keep compatibility with non-browser rendering environments like Extensions, Electron, NativeScript, etc.

Providing a callback is also tricky, because you cannot just pass a function to us via Node.js to execute in the browser - it would at least have to be a file containing a specific function (similar to what we do for the error overlay).

> I can see it's a little tricky problem due to GraphQL and other exports that are still valid. This only becomes a problem when the root of the tree isn't pure React as then the logic will fall through.

The tricky part to me is that sometimes update propagation is the desired behaviour. I have a root component mounting all routes, and I want the routes to have their data fetching logic collocated inside the same file whilst also exporting for external consumption. Firing a warning for each file penalises these use cases which led to my reluctance.

The root is almost always non-pure React because it does not have any exports - you'll just be doing `ReactDOM.render(<Something />, root)`.

**Comment by bebraw** [comment]
> This is actually already configurable - in this plugin we do not control what would happen on a bail out. If you're using the WDS for example, you could use hotOnly instead of hot, and it would only warn you when it is forced to bail out, but will not actually refresh the page. We intentionally do not hold any constraint on this to keep compatibility with non-browser rendering environments like Extensions, Electron, NativeScript, etc.

Yeah, this is my current direction. I plan to add a bit more flexibility to **webpack-plugin-serve** so that refreshing on failure will become possible. It's a small change for their runtime and it can be that's the right place to manage all this.

> Providing a callback is also tricky, because you cannot just pass a function to us via Node.js to execute in the browser - it would at least have to be a file containing a specific function (similar to what we do for the error overlay).

Yeah, I see, because this would most likely imply bundling and add complexity. 😄 

> The root is almost always non-pure React because it does not have any exports - you'll just be doing ReactDOM.render(<Something />, root).

Yeah, that's true.

I have a client-case where they use React to render web components and as it happens it seems fairly common there to have `ReactDOM.render` and then some web component logic in the same file that's the being exposed.

That said, that's a special case and it doesn't apply most of the users.

**Comment by pmmmwh** [comment]
> Yeah, this is my current direction. I plan to add a bit more flexibility to webpack-plugin-serve so that refreshing on failure will become possible. It's a small change for their runtime and it can be that's the right place to manage all this.

That would be great!

We tap into integrations for that purpose too, so if the integration support some behaviour it would be supported OOTB here, but if they don't it is best to have them support it instead of us so it would be aligned for their consumers.

> Yeah, I see, because this would most likely imply bundling and add complexity. 😄

Yup - that's what I really want to avoid for most use cases. In the best scenario I would love to have Webpack support this natively so we can tap into it as a callback (currently it requires implementing a custom hot client, which is not what everyone would do) ...

**Comment by bebraw** [comment]
I solved this by adding a `refresh-on-failure` option to webpack-plugin-serve. Reference: https://www.npmjs.com/package/webpack-plugin-serve#hmr .
