### ISSUE TITLE
Consider defaulting overlay option to false

### ISSUE THREAD

**Issue by petermikitsh** [pmmmwh/react-refresh-webpack-plugin#210]
I migrated from the deprecated react-hot-loader to this tool, and I was only expecting to have fast refresh functionality.

When I experienced my first stack trace in development after installation, the overlay felt unexpected and a bit outside the tool's primary focus.

I am unsure if my experience echos others-- regardless, thanks for considering my feedback!

**Comment by jmeistrich** [comment]
This threw me off when I first used this too. I rather like having an overlay but I think it's far too big by default. For what it's worth, I put this style on my page which makes it much less aggressive.
```
#wps-progress {
    width: 50px !important;
    height: 50px !important;
    right: 1% !important;
    top: 1% !important;
}

**Comment by pmmmwh** [comment]
> When I experienced my first stack trace in development after installation, the overlay felt unexpected and a bit outside the tool's primary focus.

The bundled overlay is considered part of the integration. Think of fast refresh as a full feedback loop: not only it does HMR for React-related code but it also helps surface warnings and errors in development so that you can immediately take action. We do not want to magically recover from errors without you ever knowing that there is an error in the first place. It is opinionated, hopefully in a good way (that's what I thought at least).

**Comment by pmmmwh** [comment]
> This threw me off when I first used this too. I rather like having an overlay but I think it's far too big by default. For what it's worth, I put this style on my page which makes it much less aggressive. Or you could put in a display: none to hide it.
> 
> ```
> #wps-progress {
>     width: 50px !important;
>     height: 50px !important;
>     right: 1% !important;
>     top: 1% !important;
> }
> ```

This is definitely not related to this plugin - `wps-progress` is injected by `webpack-plugin-serve`'s `progress` flag.
