### ISSUE TITLE
Feature Request: safeThis.__reactRefreshInjected respects webpack library name

### ISSUE THREAD

**Issue by tianjianchnbytedance** [pmmmwh/react-refresh-webpack-plugin#239]
Under micro frontend architecture, there will be multiple webpack instances run simultaneously in the same client. Like webpack doing, it appends `output.library` in config to some global variables, like `webpackHotUpdate`, `webpackJsonp`. 

For Example, for project Demo while setting `output.library` to `demo`, `webpackHotUpdate` becomes `webpackHotUpdatedemo`, `webpackJsonp` becomes ``webpackJsonpdemo`.

So, is it possible that this plugin also make the same rule for `__reactRefreshInjected`? Otherwise, it will not work with such case mentioned above.

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/client/ReactRefreshEntry.js#L5

**Comment by pmmmwh** [comment]
Hi, I wanted to know more about the use case. Does Webpack's single runtime chunk feature not solve this issue? How would you share packages across multiple micro frontends?

**Comment by tianjianchn** [comment]
@pmmmwh It's not related about webpack's single runtime chunk or packages sharing. Each micro frontend project is a separate code repo, having its own webpack instance and using its own react-refresh runtime. They are running together by 
 responding url changing and rendering its DOM while matched.

So, in this case, there will be multiple react-refresh and react-refresh-webpack-plugin running simultaneously or in sequence.  But after one micro frontend loaded, other's react-refresh wouldn't be injected since `__reactRefreshInjected` was already `true`.

For now, I have to use code below to escape the following `__reactRefreshInjected` check:
```js
const InjectPlugin = require('webpack-inject-plugin').default;

// webpack plugins, normAppId is the webpack config output.library
  new InjectPlugin(()=>{
      return `window.__reactRefreshInjected = true;
      if(!window.__reactRefreshInjected${normAppId}) {
        const RefreshRuntime = require('react-refresh/runtime');
        RefreshRuntime.injectIntoGlobalHook(window);
        window.__reactRefreshInjected${normAppId} = true;
      }
      `
    })
```

I was just wondering whether it's better or possible to do like `webpack-dev-server` doing with `webpackHotUpdateXXX`.

**Comment by pmmmwh** [comment]
So essentially you're running multiple instances of React and ReactDOM on the same page?

**Comment by tianjianchn** [comment]
Sometimes are, sometimes not, which were determined by whether there are two or more micro frontend projects matching current page url. But here we can assume that it's `are`.

**Comment by pmmmwh** [comment]
@tianjianchn So ... when there are multiple copies of React, does React Developer Tools work for you?

@gaearon Is injecting multiple copies of `react-refresh` actually safe to do given that they're from separate bundles and a different script? It's been a while since I've looked at code for dev tool hooks ...

**Comment by tianjianchn** [comment]
@pmmmwh It works😺. There are multiple FiberRoot objects and thus multiple root components in React Dev Tools's Components view.
