### ISSUE TITLE
TypeError: Cannot read property 'exports' of undefined function getModuleExports(moduleId) {   return __webpack_require__.c[moduleId].exports; }

### ISSUE THREAD

**Issue by liuhaidi1209** [pmmmwh/react-refresh-webpack-plugin#245]
My app encountered the following error when I tried integrating @pmmmwh/react-refresh-webpack-plugin.
"@pmmmwh/react-refresh-webpack-plugin": "0.4.2",

![image](https://user-images.githubusercontent.com/16359954/97874554-1e6f4880-1d54-11eb-85cf-9d969db57e4b.png)

https://user-images.githubusercontent.com/16359954/97874554-1e6f4880-1d54-11eb-85cf-9d969db57e4b.png

**Comment by HOUCe** [comment]
Anyone could give this issue a little love plz? Got the same problem here when I upgraded Create-react-app to 4.0.0

**Comment by pmmmwh** [comment]
Hi. For me to be able to look into issues, I would need more information about the actual setup. Things like Webpack version, how your app is being structured, etc. If possible a reproducible example would help with triaging a lot.

The error itself to me seems like the Webpack `module.cache` is not defined - so either it was not provided by Webpack to the module (because we did not declare it - I think explicit declaration for stuff like this is required in Webpack 5), or your module cache is corrupt.

**Comment by pmmmwh** [comment]
Hi, I did a bit of digging and I think if you have **ANY** variable named `module` within your project it will crash Webpack.

**Comment by scristobal** [comment]
it solved my problem and made my day, thank you @pmmmwh !!

**Comment by iMoses-Apiiro** [comment]
@pmmmwh seems that this bug is still happening, so why is this issue closed?

**Comment by pmmmwh** [comment]
> @pmmmwh seems that this bug is still happening, so why is this issue closed?

Do you have a variable named module? That is working as intended, reusing special Webpack injected variables will break things as expected.

**Comment by iMoses-Apiiro** [comment]
You're talking about a global `module` variable as part of the commonjs standard, or any local variable named `module` would break?

**Comment by pmmmwh** [comment]
> You're talking about a global `module` variable as part of the commonjs standard, or any local variable named `module` would break?

As far as I know, any module-level declaration of `module` would break. I haven't tested local variables, maybe this is fixable if we change how we would search for exports, but no guarantees.

**Comment by pmmmwh** [comment]
A change is now in place - exports failures will now warn in console instead of throwing.

**Comment by kryops** [comment]
I ran into this via https://github.com/callstack/linaria/issues/891.
Apparently for some kinds of virtual modules webpack does not provide a `moduleId` at all (see https://github.com/callstack/linaria/issues/891#issuecomment-1000237132).

With the change from https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/546, everything seems to be working fine again, however now I get lots of warnings in my console 😅 

@pmmmwh Is `moduleId === undefined` a special case where it would be possible to skip the warning and just ignore the module?

**Comment by pmmmwh** [comment]
> @pmmmwh Is `moduleId === undefined` a special case where it would be possible to skip the warning and just ignore the module?

In theory, the better approach would be to exclude these virtual modules to be processed by our loader, I'm not sure if that would work (if there is even some kind of pattern we can ignore against) in you case though.

Silencing warnings could be a way out, since moduleId being undefined is essentially an indicator of special types of modules where we will not be able to capture exports anyways, so we could probably also do that.

**Comment by nicholasio** [comment]
> > @pmmmwh Is `moduleId === undefined` a special case where it would be possible to skip the warning and just ignore the module?
> 
> In theory, the better approach would be to exclude these virtual modules to be processed by our loader, I'm not sure if that would work (if there is even some kind of pattern we can ignore against) in you case though.
> 
> Silencing warnings could be a way out, since moduleId being undefined is essentially an indicator of special types of modules where we will not be able to capture exports anyways, so we could probably also do that.

I am running into a similar issue where react fast refresh is being injected in a CSS virtual module and I'm trying to figure out how to exclude those "virtual modules" from react fast refresh. 

Currently exclude/include only looks into `moduleData.resource` and `moduleData.matchResource`.

Based on what I found, we'd need to look into `moduleData.request`.
See https://github.com/callstack/linaria/issues/897#issuecomment-1426033881

I've found that for a file named `example-block/edit.js` linaria generates `./includes/blocks/example-block/edit.linaria.module.css!=!../../node_modules/@linaria/webpack-loader/node_modules/@linaria/webpack5-loader/lib/outputCssLoader.js?cacheProvider=!./includes/blocks/example-block/edit.js`

but `moduleData.resource` and `moduleData.matchResource` still refers to the original JS file `./includes/blocks/example-block/edit.js`.

I was able to work around my issue by simply excluding and `moduleData.request` that includes ` \outputCssLoader\.js/ ` since that's what Linaria uses.

Any thoughts on this? would it make sense to match against `moduleData.request` as well so that we can exclude things in user-land.
