### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by natew** [pmmmwh/react-refresh-webpack-plugin#255]
So using speed-measure-webpack-plugin I see this:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/12100/99160429-20ae9c80-269c-11eb-9ffd-aa1c38ff6ff2.png">

Though I'm not sure it's accurate, because it says total compilation time was 19 seconds, and it shows another plugin takes 16 seconds. So maybe something off there, but just wanted to open an issue to potentially track landing a few performance improvements.

**Comment by swk777** [comment]
It does take a lot of time.

**Comment by mattkrick** [comment]
Build time with babel + plugin: 26s
Build time with babel: 11s

I can spend a couple days on this during the winter break. Anyone do some digging on what piece is causing the slowdown?

**Comment by pmmmwh** [comment]
For what it's worth, I think there could potentially be a few spots where the performance would degrade:

1. The loader - we inject a custom loader for all files that would match the include/exclude criterion, and that loader would process all files by injecting the refresh template to each file.
2. The parser - we replace all calls to `$RefreshReg$` and `$RefreshSig$` and their counterparts to calls to our attached helpers in the Webpack runtime, so that means token swapping all of these constants.
3. The runtime generation - not sure about this one but we do alter Webpack's main template, but that in theory should only happen once.

Unfortunately I do not have a lot of capacity to do more profiling at the moment during the holidays.

A new version `0.5.0` is in the works right now, it would be great if we can have performance enhancements cut the release but I also don't want to block the bug fixes and features - so let's see if we can find fixes soon enough.

**Comment by Slapbox** [comment]
@pmmmwh thanks so much for sharing your work. Is there somewhere we can follow progress on `0.5.0`?

**Comment by pmmmwh** [comment]
Hi, you can check out the latest beta release. Unfortunately for the past three weeks I didn't have as much time as I wanted to work on the project, but I'm hoping to complete some of the unfinished pieces on my local machine and cut a release within February.

**Comment by kaiyoma** [comment]
Today I tried switching to this plugin from react-hot-loader and the results were pretty terrible. For reference, when I start up the webpack dev server today, it takes about 2 1/2 minutes (~150 seconds) and the CPU usage hangs around 50% during compilation:

![image](https://user-images.githubusercontent.com/10719780/128433243-62523a65-7589-4d34-85c9-24910b8cab12.png)

After switching to react-refresh and trying to start the dev server, my CPU was pegged at about 90%:

![image](https://user-images.githubusercontent.com/10719780/128433344-00f600b2-2c43-466e-bc31-ccd8aaaed934.png)

I let this run for about *10 minutes* and it never made it past 68% or so, at which point I gave up for the sake of saving my laptop from meltdown. This plugin needs a lot more work before it's ready for primetime.

**Comment by Slapbox** [comment]
@kaiyoma if you're waiting _10 minutes_ it's not a performance issue unless your project is *absolutely enormous.* More likely there's some edge case you've found that leads to endless hanging.

**Comment by kaiyoma** [comment]
Yes, it is a large project. Over 4,700 source files, over 550k lines of code. I can see the filenames changing during webpack compilation, so something is definitely happening, but the percentage doesn't move above 70% and the CPU continues to run like crazy. I don't think compilation has hung; it's just really, really slow.

**Comment by Slapbox** [comment]
I hit a situation with Webpack once that lead to what seemed like an infinite recursion, somehow. In that case though, we were parsing a 3mb file as a source file though, I think.

We have ~1000 source files and ~75,000 SLOC and I don't have any trouble with the plugin on my rather old development machine, though it may indeed be slower than not using the plugin. 

Unless you're using an HDD, it really sounds like something's gone wrong - but I'm no Webpack expert.

**Comment by pmmmwh** [comment]
To be honest I cannot provide much help on performance without looking into the whole build pipeline.
What version of Webpack/React/this plugin are you on? Are you running ESM/CJS?

The way `react-refresh` works in Webpack is a 4-step process:

1. The Babel plugin `react-refresh/babel` processes specified source files, which would inject calls to RR specific lifecycle hooks as well as parsing components
2. This plugin would then run all specified source files (`include`/`exclude`) through a loader, in which we would inject a HMR runtime (module init/cleanup) for each file we've parsed. This can be potentially expensive if you use source maps + have a lot of files, since each and every file needs to pass through the loader. I'm not aware of any methods to make this faster, the loader should already cache via Webpack.
3. This plugin re-writes all calls to RR lifecycle hooks to what we've hoisted on Webpack's global scope and injects a few globals - again, we're using `DefinePlugin` and `ProvidePlugin` semantics to do this, so I'm not sure if there's much to optimise if the number of files are really high.
4. In runtime (browser/whatever runtime), each changed file when HMR-ed would go through the whole lifecycle, and changes would propagate like normal Webpack HMR except if changes are accepted it will trigger a re-render in React if we didn't bubble to root.

As you can see, most paths scale with the number of files, so when you have a lot of files it definitely adds up, but I would doubt that ~5000 files would cause a meltdown.

**Comment by kaiyoma** [comment]
@pmmmwh Webpack 4.44.2, React 16.14.0, latest versions of react-refresh and this plugin.

**Comment by JP250552** [comment]
We are seeing similar behavior (high cpu, slow compilation) with 4500+ files. 

React 17.0.2
webpack 5.37.0
react-refresh 0.10.0
react-refresh-webpack-plugin 0.4.3

**Comment by qiqiboy** [comment]
Is it related to `devtool` option? In my test(4k+ files, 500K lines):

* devtool = `cheap-module-source-map`(the source maps quality is `original` or `original lines`), the compilation time was about 400+ seconds
* devtool = `eval`(source maps quality is `generated` or `transformed`), the compilation time is ok, ~100 seconds

**Comment by pistachiomatt** [comment]
Is this issue entirely resolved? With no sourcemaps turned on speed-measure-webpack-plugin is still reporting 10s for this plugin in my repo. Is this just the nature of the beast?

**Comment by pmmmwh** [comment]
> Is this issue entirely resolved? With no sourcemaps turned on speed-measure-webpack-plugin is still reporting 10s for this plugin in my repo. Is this just the nature of the beast?

Without more details in the setup I cannot comment on the situation. Is your build 10s faster without this plugin?

**Comment by Slapbox** [comment]
Fwiw I have not noticed any difference in build times. @pistachiomatt what if you time it yourself rather than relying on `speed-measure-webpack-plugin`?

**Comment by pistachiomatt** [comment]
Okay you were right that the `speed-measure-webpack-plugin` implied loading time was sequential but it actually was concurrent. En/disabling `react-refresh-webpack-plugin` saved ~1s which is negligible. 

Also, for others following along from the future, enabling `cacheDirectory: true` to `babel-loader` also halved my loading time overall and for `react-refresh-webpack-plugin`.

Thanks!
