### ISSUE TITLE
Does not rerender with webpack 5 + babel 7 (test repo included)

### ISSUE THREAD

**Issue by franz-ka** [pmmmwh/react-refresh-webpack-plugin#293]
Hi. I can't get to work the live refresh. My setup is:
```
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/preset-react": "^7.12.10",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
    "babel-loader": "^8.2.2",
    "react-refresh": "^0.9.0",
    "webpack": "^5.13.0",
    "webpack-cli": "^4.3.1",
    "webpack-dev-server": "^3.11.2"
  }

```

I get the following text on the console on firefox:
```
[WDS] App updated. Recompiling...
[WDS] App hot update...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./src/test-component.js
[HMR] App is up to date.
```

But the content does not update.

You can see my webpack config and a test repo i did in: https://github.com/franz-ka/react-refresh-test

I also tested with `webpack-dev-server@4.0.0-beta.0` without luck.

Thx, hope i can use this plugin because i wish to migrate from hot-reloader!

**Comment by franz-ka** [comment]
When changing webpack's versions as in [your example](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/examples/webpack-dev-server)
```
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
```

The problem gets solved

**Comment by momesana** [comment]
Same for me. Simply doesn't work with webpack5. It's sufficient to solely downgrade webpack to make it work again but that's merely a workaround and not a solution.

**Comment by franz-ka** [comment]
> I had the same issue but could resolve it by setting target: "web" in my webpack config as described here or [here](https://github.com/webpack/webpack-dev-server/issues/2758) or [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/235)

The example i provided has that option setted and still doesn't work. I also tried with `webpack-dev-server@4.0.0-beta.0` but it has the same problem. What am i doing wrong?

**Comment by pmmmwh** [comment]
I'll take a look at this during the weekend!

**Comment by momesana** [comment]
@franz-ka 
I don't think this is an issue with this plugin. In fact your code works for me (I've checked out your git repo) when I apply a few tiny changes.

**Comment by franz-ka** [comment]
> @franz-ka
> I don't think this is an issue with this plugin. In fact your code works for me (I've checked out your git repo) when I apply a few tiny changes.

great, could you tell me those changes you did so i can reproduce them? thx

**Comment by momesana** [comment]
@franz-ka 
Yeah, sure. It just took a few minutes to make the changes visible and minimal in a fork (https://github.com/momesana/react-refresh-test) of your repo.

In a nutshell:
1. The example was not runnable in the browser by itself as the index.html file was missing. I had to add the html-webpack-plugin to make that work. (https://github.com/momesana/react-refresh-test/commit/7f611f3fe7b833a593b1d15e7ca607a3630e8df3)
2. Secondly -- and that is the fix to your problem --, your webpack.config.js lacked an entry point which is important as it turns out. With the entrypoint in place it works. (https://github.com/momesana/react-refresh-test/commit/d5a5915e0d3bd659f6a0cc60570f9892a2e9d50a)
3. You don't need the module.hot check and accept call to make it work. So I removed it in a third commit.(https://github.com/momesana/react-refresh-test/commit/887d67ff9fe417026f2d2e2313696ae245990da5)

**Comment by pmmmwh** [comment]
@momesana thanks for spotting this!

I do think we would throw if no entry point is detected. This probably is a bug and I'll take a look.

**Comment by franz-ka** [comment]
@momesana 
wow i can't believe that was the problem, thx! adding an entry point to `webpack.config.js` effectively solves the issue :+1:

**Comment by pmmmwh** [comment]
Error will now be thrown in `0.5.0-beta.1`.
