### ISSUE TITLE
Get websocket port from `document.currentScript` if possible

### ISSUE THREAD

**Issue by mmhand123** [pmmmwh/react-refresh-webpack-plugin#30]
Sorry if this is a duplicate. I saw there was #10 but I think this is a little different. With `webpack-dev-server` we're running it off another port locally. I looked at how `wds` tries to establish the socket and noticed `__resourceQuery`, but also that it falls back to trying to use `document.currentScript`. For the time being would it be ok to add in trying to parse `document.currentScript` and fall back to the current behavior? Happy to PR this, just wanted to check if it was something you'd want 😁

**Comment by pmmmwh** [comment]
Yea - this is something on my radar. I do have a TODO in the source code tracking this. I'm also waiting for webpack/webpack-dev-server#2055 to land so that public path can be properly supported. I have some code written already - if you want to pick this up I can share them cause atm I'm focusing on #7 and #10

**Comment by markovicdenis** [comment]
Another idea would be to add settings options for "hostname" and "port" for the socket connection... 

In my particular configuration, the deserver is running on different port with different hostname as well.

**Comment by mmhand123** [comment]
@pmmmwh yeah I'd be happy to pick it up and work on it. Would be great to see what you've already done!

@markovicdenis Yeah - you can actually get those from `document.currentScript` too. I just mentioned port because it was the thing custom in the webpack config I was working with :sweat_smile: Could potentially do both though, add the options and fallback to current script or something.

**Comment by jcdhomes** [comment]
@mmhand123  I was able to utilize the `sockPath` and `sockPort` config items from the `devServer` config to setup the socket in `createSocket.js` using `__resourceQuery`.   I didn't have any luck with `document.currentScript` because it always just returned the name of the bundle this entry file ends up in and doesn't include the added query.  (ie `main.bundle.js`).

@pmmmwh Would you like a PR for this?

**Comment by carrickjason** [comment]
@mmhand123  I was able to utilize the `sockPath` and `sockPort` config items from the `devServer` config to setup the socket in `createSocket.js` using `__resourceQuery`.   I didn't have any luck with `document.currentScript` because it always just returned the name of the bundle this entry file ends up in and doesn't include the added query.  (ie `main.bundle.js`).

@pmmmwh Would you like a PR for this?

**Comment by ro-savage** [comment]
@carrickjason - Would be great if you could do a PR for this. We are running into the same issue.

**Comment by pmmmwh** [comment]
> @pmmmwh Would you like a PR for this?

Yes, it would help. [This implementation](https://github.com/Loonride/webpack-dev-server/blob/public-path-fix/client-src/default/utils/getUrlParts.js) could also help - it seems to fit our use cases well in terms of handling custom servers and also `_resourceQuery`.

**Comment by ro-savage** [comment]
When I tried to access `__resourceQuery` inside `createSocket.js` it just comes back as null.
Using `document.currentScript` no port is provided (at least on our implementation of webpack using rail's webpacker).

I'd wouldn't mind trying to implement this, but at a bit of a loss. Unless we just allow custom ports.
