### ISSUE TITLE
Hot reloading tested in different ways and is not working properly

### ISSUE THREAD

**Issue by Ridermansb** [pmmmwh/react-refresh-webpack-plugin#303]
- **Operating System:** _macOS Big Sur 11.2_
- **Node Version:** _v14.15.4_
- **NPM Version:** _6.14.10_
- **webpack Version:** _^5.19.0_
- **webpack-dev-server Version:** _^4.0.0-beta.0_
- **Browser:** _Google Chrome Version 88_

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

Repository link: https://github.com/Ridermansb/webpack5Hot

 - [`master`](https://github.com/Ridermansb/webpack5Hot) branch it's using only basic webpack-dev-server configuration without any plugins
 - [`react-hot-loader`](https://github.com/Ridermansb/webpack5Hot/tree/react-hot-loader) branch it's using [react-hot-loader](https://github.com/gaearon/react-hot-loader) plugin. **[Pull Request #1](https://github.com/Ridermansb/webpack5Hot/pull/1)**
 - [`react-refresh-webpack-plugin`](https://github.com/Ridermansb/webpack5Hot/tree/react-refresh-webpack-plugin) branch it's using [pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin) webpack plugin. **[Pull Request #2](https://github.com/Ridermansb/webpack5Hot/pull/2)**

### Expected Behavior

In all case... should not reload the page and only reload the portion that's changed

### Actual Behavior

It's Always reloading the entire page.

### For Bugs; How can we reproduce the behavior?

Just clone the repository [ridermansb/webpack5Hot](https://github.com/Ridermansb/webpack5Hot) 

 - `npm install`
 - `npm start`

And try update `Header` component

**Comment by pmmmwh** [comment]
Hi, if you add your entry to your `webpack.config.js` it will work.

**Comment by pmmmwh** [comment]
Error will now be thrown in `0.5.0-beta.1`.

**Comment by FlavioMH** [comment]
@pmmmwh Sorry to write here on a closed issue, but I get a behaviour that is exactly the same @Ridermansb described on his [demo.gif](https://github.com/Ridermansb/webpack5Hot/blob/master/demo.gif)
Different from his sample, I have an entry in my `webpack.common.js` config file (no errors shown on `0.5.0-beta.8`).

I put a sample on this repo [FlavioMH/webpackDevServer4HMR](https://github.com/FlavioMH/webpackDevServer4HMR)
Repository has been created starting from a bigger project, so you can find out some webpack settings or package.json entries not used in this sample (bigger project works with React, Redux, Typescript).

-----
- **Operating System:** _Windows 10 Pro 20H2 - x64_
- **Node Version:** _v14.17.0_
- **NPM Version:** _6.14.13_
- **webpack Version:** _5.37.1_
- **webpack-dev-server Version:** _4.0.0-beta.3_
- **webpack-cli** _4.7.0_
- **@pmmmwh/react-refresh-webpack-plugin** _0.5.0-beta.8_
- **Browser:** _Google Chrome Version 90_

### Expected Behavior

Before to update to webpack v5, I was using webpack v4 with webpack-dev-server v3.11.2. I was also using react-hot-loader and expected behavior was:
- listing on Visual Studio Code console files affected by reload
- listing on developer tools console files affected by reload
- browser not to refresh whole page, but only changed label

### Actual Behavior

Once I save the file, never mind about what change I am doing, browser immediately shows tabl loading spinner and the enite page is refreshed.
This happens even if HMR seems to be activated.

### How can we reproduce the behavior?

1. Clone the repository [FlavioMH/webpackDevServer4HMR](https://github.com/FlavioMH/webpackDevServer4HMR)
2. `npm install`
3. `npm run app`
4. Try to change _"Try to change this label and everything will refresh..."_ sentence into `testApplication.tsx` file 


Is this an issue with another package? Maybe `webpack-dev-server` one?

**Comment by pmmmwh** [comment]
I'll take a look tomorrow.

**Comment by FlavioMH** [comment]
@pmmmwh Sorry to bore you...any news on this?

**Comment by pmmmwh** [comment]
@FlavioMH This has nothing to do with the plugin. It is probably either something wrong in your Webpack setup, or a bug from WDS.

If you just persist the logs from hot reloading (simply by running `hot=only` or just use dev tools persist logs) you can see that WDS is complaining that the content base was not properly set and is lost on every update:

<img width="410" alt="Screenshot 2021-05-31 at 00 13 38" src="https://user-images.githubusercontent.com/9338255/120121709-449f7e80-c1a5-11eb-9e8f-d78e12ffe5a1.png">

Which, when I do `devServer.devMiddleware.writeToDisk` to print out files, there seem to be a directory problem where some names are `undefined` and thus not recognized properly:

<img width="246" alt="Screenshot 2021-05-31 at 00 14 23" src="https://user-images.githubusercontent.com/9338255/120121710-45381500-c1a5-11eb-9ef6-d214d09b9a95.png">
