### ISSUE TITLE
Automatic refresh silently fails with .browserslistrc

### ISSUE THREAD

**Issue by ps-aux** [pmmmwh/react-refresh-webpack-plugin#385]
When `.browserslistrc` is present in the directory -  either empty or with following content

```
# Browsers that we support

defaults
not IE 11
#maintained node versions
```

the refresh won't work and without issuing a working.

If `maintained node versions` setting is uncommented it will fail with
>  Error: Universal Chunk Loading is not implemented yet

**Comment by pmmmwh** [comment]
I presume you're using Webpack 5 since it's the only Webpack version that supports Browserlist.

This is a bug from `webpack-dev-server` v3 which does not parse the `target` correctly.

You can either:

1. Set `target` to `web` in development mode and use `browserslist` in production mode; or
2. Use `webpack-dev-server` v4 beta, and set `sockProtocol` as `ws` (This is a breaking change on their side that we do not officially support yet).

For the universal chunk loading algorithm - this is a missing feature in Webpack. Please report there if you want it to happen.
