### ISSUE TITLE
__REACT_DEVTOOLS_GLOBAL_HOOK__ doesn't installed when there is no entry in the config

### ISSUE THREAD

**Issue by Jack-Works** [pmmmwh/react-refresh-webpack-plugin#398]
By default, webpack will have a default entry `main: ./src/index`. If I use that default entry, `__REACT_DEVTOOLS_GLOBAL_HOOK__ ` will not be installed thus I cannot use react-refresh

**Comment by pmmmwh** [comment]
Webpack 5 or Webpack 4? If the former this is intentional and an artificial constraint right now. It is simply not safe to update the entry after any compiler hooks has run in Webpack 4, and since it works most of the time when you have an entry specified in Webpack 5 I'm not putting this on top of the priority list now.

#319 would fix this.

**Comment by Jack-Works** [comment]
It's webpack 5. I guess it should be well documented or it will be very confusing to find out why hmr does not working.

**Comment by pmmmwh** [comment]
I'll finish up #319 - manage to get it somewhat working.
