### ISSUE TITLE
Could we set react-refresh as normal dependency?

### ISSUE THREAD

**Issue by AoDev** [pmmmwh/react-refresh-webpack-plugin#418]
At the moment I don't see why `react-refresh` is a peer dependency (?)

I think it should be a normal dependency. This would simplify the installation and ensure that the right version is installed with react-refresh-webpack-plugin.

If there is something I'm missing, let me know. Thank you for your plugin : )

**Comment by pmmmwh** [comment]
It has to be peer because it needs to be installed in your app's `node_modules` instead of the plugin's `node_modules` - we inject code into your app that will get bundled, and `react-refresh` is effectively within your app and not something we can control. Also note that you need to wire up `react-refresh/babel` yourself.

**Comment by AoDev** [comment]
ok I see. Thanks.
