### ISSUE TITLE
404 with http://localhost:3000/sockjs-node/info?t=...

### ISSUE THREAD

**Issue by MOZGIII** [pmmmwh/react-refresh-webpack-plugin#43]
This plugin produces requests to `http://localhost:3000/sockjs-node/info?t=...` for me (valid host/port!) that end up with 404.
It doesn't seem like my server serves this endpoint. I'm using `electron-forge`.

The actual reloading works.

Is there a way to stop those info requests for running, so they don't show up as errors? It seems like there should be a `noInfo` option for the socket...

**Comment by pmmmwh** [comment]
Hi - I have no knowledge on `electron-forge` or `electron`-related development in general. It would be great if you can provide a reproduce-able example somehow so that I can investigate further. To my understanding, if the socket request is resulted in a `404`, the reloading wouldn't work properly on Webpack recompile, so I would also appreciate if you can further elaborate what you mean by "the actual reloading works".

**Comment by ro-savage** [comment]
@pmmmwh - this is probably the same issue as  #40 and possibly #30

And despite this 404 error, react-refresh works as expected (at least as best I can tell). There is just a bunch of errors in the console.

**Comment by blainekasten** [comment]
This is solved with #23 as the socket initialization is behind a flag now

**Comment by MOZGIII** [comment]
@blainekasten  `useLegacyWDSSockets` - tried enabling it, doesn't seem to help. Am I missing something?

**Comment by MOZGIII** [comment]
Here are the screenshots of the networking panel to give you some idea on what's going on:
![image](https://user-images.githubusercontent.com/265507/75693612-3fa90200-5cb8-11ea-9618-5929ffee54f0.png)
![image](https://user-images.githubusercontent.com/265507/75693727-6ff0a080-5cb8-11ea-9991-3e8970e366a1.png)

And from console:
![image](https://user-images.githubusercontent.com/265507/75693863-ae865b00-5cb8-11ea-87a4-bb76cd894fec.png)

**Comment by pmmmwh** [comment]
> @blainekasten `useLegacyWDSSockets` - tried enabling it, doesn't seem to help. Am I missing something?

Just released the fix in `v0.2.0`, mind trying that and see if it helps? From what I see from their source code, `electron-forge` uses `webpack-hot-middleware` out of the box, and that is not officially supported properly until now.

Other than that, I think the underlying cause might be due to us not handling `__resourceQuery` right now (it's on my todo list). For WDS, webpack/webpack-dev-server#1385. webpack/webpack-dev-server#2055 was supposed to fix that but since it is breaking they are delaying the release.

**Comment by MOZGIII** [comment]
> `electron-forge` uses `webpack-hot-middleware` out of the box

This is right, here's a tracking issue at their repo: https://github.com/electron-userland/electron-forge/issues/1530.

Since I got feedback from both ends, I see the possibility of figuring out a proper solution together.

**Comment by pmmmwh** [comment]
> > `electron-forge` uses `webpack-hot-middleware` out of the box
> 
> This is right, here's a tracking issue at their repo: [electron-userland/electron-forge#1530](https://github.com/electron-userland/electron-forge/issues/1530).
> 
> Since I got feedback from both ends, I see the possibility of figuring out a proper solution together.

Did 0.2.0 work for you? It should not use SockJS if WHM is present, but I won't be able to confirm this until I setup a full electron dev environment this weekend.

**Comment by MOZGIII** [comment]
0.2 yields interesting results. New odd errors. Definitely worth creation a sample repo with a minimal example to play with.
