### ISSUE TITLE
Why not use it?"@next/react-refresh-utils"

### ISSUE THREAD

**Issue by masx200** [pmmmwh/react-refresh-webpack-plugin#463]
Why not use it?"@next/react-refresh-utils"
```js
        const ReactRefreshWebpackPlugin =
            require("@next/react-refresh-utils/ReactRefreshWebpackPlugin").default;
        config.entry = [
            require.resolve("@next/react-refresh-utils/runtime"),
            ...config.entry,
        ];
        config.plugins = [new ReactRefreshWebpackPlugin(), ...config.plugins];
        config.module.rules = [
            {
                test: /\.(tsx|ts|js|mjs|jsx)$/,
                include: [srcfoldepath],
                exclude: [/node_modules/],
                use: [require.resolve("@next/react-refresh-utils/loader")],
            },
            ...config.module.rules,
        ];
```

**Comment by xiongcaihu** [comment]
not work with React.lazy

**Comment by masx200** [comment]
> not work with React.lazy

Can you elaborate on why?

**Comment by JPeer264** [comment]
I was curious and tried it as proposed, but got following error:

```
Error: ReactFreshWebpackPlugin does not support webpack vNaN.
    at ReactFreshWebpackPlugin.apply (/Users/user/project/node_modules/@next/react-refresh-utils/ReactRefreshWebpackPlugin.js:127:23)
    at createCompiler (/Users/user/project/node_modules/webpack/lib/webpack.js:74:12)
    at create (/Users/user/project/node_modules/webpack/lib/webpack.js:127:16)
    at webpack (/Users/user/project/node_modules/webpack/lib/webpack.js:151:32)
    at f (/Users/user/project/node_modules/webpack/lib/index.js:55:16)
    at Object.<anonymous> (/Users/user/project/lib/server/devMiddleware.ts:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/user/project/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .ts] (/Users/user/project/node_modules/pirates/lib/index.js:104:7)
```

So I am not sure if this is a working drop-in replacement.

**Comment by masx200** [comment]
I use it in&nbsp; webpack5 without any problems.



---Original---
From: "Jan Peer ***@***.***&gt;
Date: Fri, Aug 20, 2021 18:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pmmmwh/react-refresh-webpack-plugin] Why not use ***@***.***/react-refresh-utils" (#463)




 
I was curious and tried it as proposed, but got following error:
 Error: ReactFreshWebpackPlugin does not support webpack vNaN.     at ReactFreshWebpackPlugin.apply ***@***.***/react-refresh-utils/ReactRefreshWebpackPlugin.js:127:23)     at createCompiler (/Users/user/project/node_modules/webpack/lib/webpack.js:74:12)     at create (/Users/user/project/node_modules/webpack/lib/webpack.js:127:16)     at webpack (/Users/user/project/node_modules/webpack/lib/webpack.js:151:32)     at f (/Users/user/project/node_modules/webpack/lib/index.js:55:16)     at Object.<anonymous&gt; (/Users/user/project/lib/server/devMiddleware.ts:10:18)     at Module._compile (internal/modules/cjs/loader.js:1063:30)     at Module._compile (/Users/user/project/node_modules/pirates/lib/index.js:99:24)     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)     at Object.newLoader [as .ts] (/Users/user/project/node_modules/pirates/lib/index.js:104:7)  
So I am not sure if this is a working drop-in replacement.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JPeer264** [comment]
Ok that is interesting, I am using it with webpack v`5.51.0`. I, however, start the dev server with the [dev-middleware](https://github.com/webpack/webpack-dev-middleware) directly.

**Comment by masx200** [comment]
> Ok that is interesting, I am using it with webpack v`5.51.0`. I, however, start the dev server with the [dev-middleware](https://github.com/webpack/webpack-dev-middleware) directly.

I started it with the "webpack serve" method.  The configuration file is like this.

https://github.com/masx200/webpack-react-vue-spa-awesome-config/blob/1e43822140b51deb778684ea677cdd9035ea9c39/lib/config.ts#L632

**Comment by pmmmwh** [comment]
Short answer:
This plugin exists way before Next.js implemented RR and we address different concerns even though the core functionality is similar. If you want something batteries included, then it's probably this plugin.

Long answer:
The Next.js version of fast refresh utilities spawned from their need to implement Webpack HMR invalidation. The team from Vercel and I (and Dan) were in touch and they decided to implement their new utilities, with close integration with their error overlay, based on the runtime implemented in this plugin back then.

Since then this plugin has evolved and diverged to provide more features (e.g. WHM/WPS support, native ESM, top level await (experimental), fully plug and play overlay), we've re-written core parts to support a wider spectrum of build setups, and we also try to be as batteries included as possible - we will do the entry injection, loader injection, etc. for you by default.

I guess it really boils down to choice, if your build setup is similar to what Next.js is running and you don't need much customisation, you could use what they have provided. However, it should also be noted that I believe they built the set of utilities to suit their specific use case, and your mileage may vary.

An addendum - you can also configure this plugin to how you've configured the Next.js utilities, if you prefer to wire up everything on your own:

```
const ReactRefreshWebpackPlugin =
            require("@pmmmwh/react-refresh-webpack-plugin");

config.entry = [
  require.resolve("@pmmmwh/react-refresh-webpack-plugin/client/ReactRefrsshEntry"),
  ...config.entry,
];
config.plugins = [
  new ReactRefreshWebpackPlugin(),
  ...config.plugins,
];
config.module.rules = [
  {
    test: /\.(mjs|[jt]sx?)$/,
    include: srcPath,
    exclude: /node_modules/,
    use: [
      require.resolve("@pmmmwh/react-refresh-webpack-plugin/loader"),
    ],
  },
  ...config.module.rules,
];
```
