### ISSUE TITLE
Loadable Components?

### ISSUE THREAD

**Issue by justin808** [pmmmwh/react-refresh-webpack-plugin#48]
Has anybody tried this plugin with [loadable-components](https://loadable-components.com/)?

I'm guessing that there will be a similar issue:

* https://github.com/gaearon/react-hot-loader/issues/1361 
* https://github.com/gregberge/loadable-components/issues/243

**Comment by pmmmwh** [comment]
Loadable was never on my radar, but fast refresh works quite differently from RHL. Nonetheless, as Anton has stated in the linked issue, class-based components will lose state upon update (this is a known constraint for FR).

I am leaning towards that it will work though - however I currently don't have capabilities to test this out since I don't use loadable myself.

**Comment by avetisk** [comment]
I'm using both together and haven't had any issues so far.

**Comment by pmmmwh** [comment]
I have verified that it works with loadable, and will persist state given that it is wrapping a function component.

**Comment by justin808** [comment]
@pmmmwh @avetisk did you try this plugin with loadable-components *and* SSR?

_React.lazy is probably preferable to loadable-components if no SSR is needed._

**Comment by pmmmwh** [comment]
> @pmmmwh @avetisk did you try this plugin with loadable-components *and* SSR?

No, but it works for CSR - so in theory it should work for SSR too. If it doesn't work, most likely it is a Webpack configuration problem rather than the plugin's problem.

**Comment by adbutterfield** [comment]
Not sure if anyone would be interested, but I have an example with SSR and loadable-components/typescript/styled-components: https://github.com/adbutterfield/fast-refresh-express
