### ISSUE TITLE
Hot Reloading not working on webpack 5.51.1

### ISSUE THREAD

**Issue by Erfan-Motallebi** [pmmmwh/react-refresh-webpack-plugin#495]
Whenever I apply the appropriate **plugins** to use, it shows _nothing_ at the end. **there are no errors when** these plugins are added.
the result of **development mode** is white.
thus, Whenever I make an infinitesimal change in **App.tsx** to test it out, it doesn't work properly.

**Comment by pmmmwh** [comment]
Can you post more information about your setup? Things like versions of Webpack, whatever HMR integration you're using, version of this plugin, your Webpack configuration, etc.

**Comment by mmykhaylov** [comment]
I don't know if I am facing this issue for the same reason that you might, but here's my [repo](https://github.com/mmykhaylov/webpack-react-boilerplate) where turning on react-refresh plugin breaks the dev page. Specifically, the error is `TypeError: Object is not a constructor (evaluating 'new SocketClient(url.format(urlParts))')`

My stack:
React 17.0.2
Webpack 5.51.1
React-refresh 0.10.0
React-refresh-plugin: 0.4.3
React-refresh-typescript": 2.0.2

To get error
1. Clone repo
2. Install dependencies
3. Run yarn dev

To get rid of error, proving that the cause is react-refresh-webpack-plugin
1. Comment out lines 38-45, 89 and 90
2. Run yarn dev

**Comment by pmmmwh** [comment]
> TypeError: Object is not a constructor (evaluating 'new SocketClient(url.format(urlParts))')

For this error please just use `0.5.0-rc` or use WDS v3.
`0.4.3` does not support WDS v4, and probably never will. It is correct that it throws, we specified the peer dependency to be `3.x`.

**Comment by paprikman** [comment]
Confirmed working with `wds4` and `0.5.0-rc`.

**Comment by includeovalle** [comment]
> Confirmed working with `wds4` and `0.5.0-rc`.

Can you elaborate first time using webpack and a hot loader im really lost here.
Im googlin' all terms I read here and yet i feel clumsy.

**Comment by pmmmwh** [comment]
> > Confirmed working with `wds4` and `0.5.0-rc`.
> 
> Can you elaborate first time using webpack and a hot loader im really lost here.
> Im googlin' all terms I read here and yet i feel clumsy.

If you have installed `0.4.3` of `@pmmmwh/react-refresh-webpack-plugin` and are using `webpack-dev-server` `4.x.x`, it is expected that the client will throw since `0.4.3` does not support `4.x.x` of WDS.

Instead, you should use our **NON-STABLE** release candidate version, `@pmmmwh/react-refresh-webpack-plugin@next`, or to be specific `0.5.0-rc.6`, which includes support for WDS `4.x.x`.

If you have other problems, feel free to open a new issue.

**Comment by pmmmwh** [comment]
I believe this issue is related to expected behaviour of `0.4.3` and resolved bug in `0.5.0`.
