### ISSUE TITLE
Unknown option: .visitor

### ISSUE THREAD

**Issue by ben-x9** [pmmmwh/react-refresh-webpack-plugin#518]
I implemented this according to the README and get the following error when I run `webpack serve`:

    Module build failed (from ./node_modules/babel-loader/lib/index.js):

    Unknown option: .visitor. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options

Unfortunately there's no other helpful information in the error log.

**Comment by joaosouza1** [comment]
I got this error too. My mistake was inadvertently inserting `react-refresh/babel` in `presets` instead of `plugins`:

❌ WRONG:

```js
// .babelrc
{
  "presets": [
    "@babel/env",
    "@babel/preset-react",
    "react-refresh/babel"
  ]
}
```

✅ CORRECT:

```js
// .babelrc
{
  "presets": [
    "@babel/env",
    "@babel/preset-react"
  ],
  "plugins": [
    "react-refresh/babel"
  ]
}
```

What's interesting is that the plugin works even if I _don't_ include `react-refresh/babel` in babel plugins, as long as I add it to webpack plugins, as shown below. I'm not sure if there's any drawback, so I'm keeping it in both places, as instructed in the README.

```js
// webpack.config.js
module.exports = {
  ...
  plugins: [
    new ReactRefreshWebpackPlugin()
  ]
}
```

**Comment by pmmmwh** [comment]
Hooks will not keep state/might throw errors if you add/remove/re-order, so its best to keep the Babel plugin there.
