### ISSUE TITLE
Docker - HMR not working

### ISSUE THREAD

**Issue by morriq** [pmmmwh/react-refresh-webpack-plugin#590]
Hello, 

I've seen https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/348 but can't agree with that.

I tried react-refresh in my project and then I take differences one by one and implement it in https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/examples/typescript-with-swc

compared with my project I had to make in ./examples/typescript-with-swc:

- remove ForkTsCheckerWebpackPlugin
- bump dependencies
-  moved swc config to  .swcrc and replace it
- implement webpack output.library functionality
- use absolute imports

after that HMR still worked!
so I tried with docker. Here you can test it: https://github.com/pmmmwh/react-refresh-webpack-plugin/compare/main...morriq:test-docker?expand=1

and it stopped working. 

it detects changes but it makes full reload instead hmr.

some logs:

```
[HMR] Waiting for update signal from WDS...
main.js:2 [webpack-dev-server] Hot Module Replacement enabled.
main.js:2 [webpack-dev-server] Live Reloading enabled.
main.js:2 [webpack-dev-server] App updated. Recompiling...
main.js:2 [webpack-dev-server] App hot update...
main.js:2 [HMR] Checking for updates on the server...
main.js:2 Fetch finished loading: GET "http://localhost:8080/main.c80fde0d65d0dfed8499.hot-update.json".
Navigate to http://localhost:8080
```

**Comment by pmmmwh** [comment]
It is not an issue with Docker:

1. Your `Dockerfile` is not getting the correct `NODE_ENV` properly - if you do `console.log(process.env.NODE_ENV)` within `webpack.config.js` you will see that it is permanently `production`. You can add this to your `docker-compose.yml`:

   ```yaml
   environment:
     NODE_ENV: development
   ```

2. Your build argument is named incorrectly - within the `Dockerfile` it is `NODE_ENVIRONMENT` but you're using `NODE_ENV` in `docker-compose.yml`

3. You did not enable the React Refresh transform from `swc`: [it is off by default even in development mode](https://swc.rs/docs/configuration/compilation#jsctransformreactrefresh).

   ```json
   {
     "jsc": {
       "transform": {
         "react": {
           "refresh": true,
           "runtime": "automatic"
         }
       }
     }
   }
   ```

5. Not sure if this is an issue, but the official Docker docs uses this form of overriding:

   ```dockerfile
   ARG         NODE_ENV
   ENV         NODE_ENV=${NODE_ENV:-production}
   ```

After applying the fixes above, the app works as expected.

**Comment by morriq** [comment]
`        "refresh": true,`

this is it. thank you for your help :)

**Comment by TheDevelolper** [comment]
There's a similar issue when using Dev Containers on Windows. Docker for Windows often uses WSL and there are some issues relating to how parts of the filesystem monitor and report changes.

I found a solution to the problem and I've written an article on how to fix it here: 
https://dev.to/simplifycomplexity/solving-hot-reload-issues-in-vs-code-dev-containers-on-windows-with-wsl2-16d5

It might be caused by the way WSL2 monitors mounted drives for changes. There's an issue where it will not do this from within a mounted drive (I don't mean a docker volume). So my article describes the steps needed to fix the issue. 

I hope my work helps anyone else facing the problem.
