### ISSUE TITLE
React module detection doesn't work unless explicitly importing 'react'

### ISSUE THREAD

**Issue by xandris** [pmmmwh/react-refresh-webpack-plugin#67]
And not 'react/index.js' or whatever. That's fine, but what I'm doing within our codebase is:

1. Babel uses `__react_createElement__` as its JSX pragma and these get injected during `babel-loader`.
2. Webpack's `ProvidePlugin` sees an unbound `__react_createElement__` and imports `node_modules/react/index.js`. (I don't know when this happens; maybe during the module templating? It's after the loaders in any case.)

But the loader in this plugin is looking for `'react'` or `"react"` in my source code. It looks in between step 1 and 2, so it sees `__react_createElement__` but not the import of React from `ProvidePlugin`.

The reason I do this is to avoid the `import react from 'react';` that we don't explicitly use in our source code, and it lets me switch between React and Preact pretty easily. You could justifiably say "don't do that" and just call it an unsupported use case, and I acknowledge that I'm going off the beaten path a bit, so I wouldn't expect something like this to be supported out of the box. However, how would you feel about giving a little bit of control over how modules are detected? The current regex of `/['"]react['"]/` could be the default, but for more _bespoke_ situations I could pass `/\b__react_createElement__\b/` or similar into the plugin options. What do you think? I'm willing to submit a pull request if you're okay with this.

(My other option is to create a loader that looks for my JSX pragma and injects `'react';` as a directive or `/*'react'*/` as a comment. I'll do that just so I can proceed, but it feels a little weird.)

**Comment by gaearon** [comment]
Yeah it's definitely not right to look for a `react` import. We're actually going to change the JSX transform to do the auto-importing so it won't' even exist in the source.

**Comment by pmmmwh** [comment]
I think there are two issues here, the first related to how we should detect a file related to React, and the second related to whether this detection makes sense.

The check was added a while back when the actual hot runtime was not as reliable, but it is somewhat redundant now because there are runtime checks for refresh boundaries before anything is being marked as hot accepted.

I'm more inclined in removing the check, which means basically all JS-like files will get processed by the loader - but this will keep stuff more deterministic and less "sniffing" (could allow users to change the file inclusion regex, so that if someone uses some other flavours of JS e.g. coffeescript they could tap into that and the whole integration still works)

As always, PRs are welcome :)

@gaearon would love you thoughts on the ideas above
 (And just out of curiosity, how would the new transform work?)

**Comment by SimenB** [comment]
New transform: https://github.com/babel/babel/pull/11154

**Comment by xandris** [comment]
I added pull request #69 to try removing the check :)

**Comment by gaearon** [comment]
I think you need to transform all JS but be careful with any imports you inject (if you inject any) to avoid circular references. You definitely want to exclude `webpack/` built-in modules from transforming regardless.

**Comment by xandris** [comment]
I can take a closer look at that. Does the refresh machinery need to transform code in node_modules to work properly?

**Comment by gaearon** [comment]
It doesn't.
