### ISSUE TITLE
Does the error overlay websocket need a ping heartbeat?

### ISSUE THREAD

**Issue by drather19** [pmmmwh/react-refresh-webpack-plugin#9]
Related to https://github.com/facebook/create-react-app/issues/8091 in the latest CRA.

The same idle timeout seems to affect the websocket used in this plugin, as well (makes sense since it's constructing the same kind of connection).

**Comment by pmmmwh** [comment]
> Related to [facebook/create-react-app#8091](https://github.com/facebook/create-react-app/issues/8091) in the latest CRA.
> 
> The same idle timeout seems to affect the websocket used in this plugin, as well (makes sense since it's constructing the same kind of connection).

I didn't notice this until you mentioned it. Pinging seems like a bad idea on first thought, will have to check how webpack-dev-server handles that.

**Comment by silverwind** [comment]
Every websocket connection should have a keepalive to prevent firewalls from terminating the connection unexpectedly. Sockjs defaults it to one ping every 25s which seems like a good default to me.

**Comment by pmmmwh** [comment]
I am pretty confident 

> > Related to [facebook/create-react-app#8091](https://github.com/facebook/create-react-app/issues/8091) in the latest CRA.
> > The same idle timeout seems to affect the websocket used in this plugin, as well (makes sense since it's constructing the same kind of connection).
> 
> I didn't notice this until you mentioned it. Pinging seems like a bad idea on first thought, will have to check how webpack-dev-server handles that.

Did a bit of further research - I think it would be best to move this upstream (to WDS/CRA) because we are just consuming sockets created by these parties generically. The implementation of a heartbeat is heavily dependent on the actual socket being used and is difficult for the overlay to control: for example, if the server did not implement handling for the 'pong' message, even if I can ping it successfully I have no confidence in whether the connection is still valid (the server could close the connection without disconnecting).

**Comment by pmmmwh** [comment]
Resolved by webpack/webpack-dev-server#2404.
